<article class="post-entry post-entry-type-standard post-entry-9446 post-loop-2 post-parity-even multi-big  post-9446 news type-news status-publish has-post-thumbnail hentry" itemscope="itemscope" itemtype="https://schema.org/CreativeWork" >
        <div class="entry-content-wrapper clearfix standard-content">

            <header class="entry-content-header">

                <span class='search-result-counter '>2</span>
                <h2 class='post-title entry-title'>
                	<a title='[field:title/]' href='http://www.insigmagroup.com.cn/news/%e5%89%8d%e6%b2%bf-%e4%bc%97%e5%90%88%e7%a7%91%e6%8a%80%ef%bc%8c%e9%a2%86%e8%b7%91%e6%99%ba%e6%85%a7%e4%ba%a4%e9%80%9a%e6%96%b0%e6%8a%80%e6%9c%af'  itemprop="headline" >[field:title/]</a>
                </h2>                
                <span class='post-meta-infos'>
                    <time class='date-container minor-meta updated'  itemprop="datePublished" datetime="2018-04-21T16:49:00+00:00" >
                    2018 - 04 - 21
                    </time>
                  	<span class='text-sep'>/</span>
                  	<span class="blog-categories minor-meta">在：  </span>
                </span>
            </header>

            <div class="entry-content"  itemprop="text" ><p>近日，由国家发改委综合运输研究所指导，北京地铁运营有限公司研发中心和RT轨道交通联合主办的“2018年中国（国际）智慧轨道交通大会”圆满闭幕！来自60多家轨道交通优秀企业，40多家地铁公司、和200多家相关厂商，共计1281名参会代表齐聚北京，探讨和交流智慧轨道交通的未来，标志着方兴未艾、如火如荼的城市轨道交通建设迅猛地向着更信息化、智慧化方向发展。 网新集团旗下众合科技，依托与浙江大学共建的国家列车智能化工程技术研究中心，潜心技术研发，在智慧交通领域取得一系列专业研究成果，众合科技作为智慧轨道交通的先行者，向大会展示了“众合智慧”。 本次大会上，众合科技在“全自动运行地铁的建设与运营管理论坛”进行主题发言。工程设计中心副总经理周根火代表众合科技向与会代表和专家介绍了“有轨电车系统信息集成与自动化运行解决方案”，方案紧密围绕智慧交通理念，首次在有轨电车领域提出了全自动运行构想并提供了详细系统解决方案，为有轨电车的智慧运营和创新管理提供了全新的概念和实践路线。 2018年，众合科技多次参与 [&hellip;]</p>
			</div>        
		</div>

        <!-- <footer class="entry-footer"></footer> -->
        
    </article><!--end post-entry-->