<div class="left"><span class="s-title">[field:title/]</span><span class="title">[field:title/]</span></div>
<div class="right">
<p><img class="pic-detail" src="[field:picname/]" alt="[field:title/]" /></p>
<div class="description">
[field:body function='cn_substr(html2text(@me),600)'/]
</div>
<div><span class="state all">查看所有</span> <span class="state hidden hiding">收起</span></div>
</div>
</div>