<article class='post-entry post-entry-type-standard post-entry-9362 post-loop-4 post-parity-even top3 post with-slider post-9362 news type-news status-publish has-post-thumbnail hentry'  itemscope="itemscope" itemtype="https://schema.org/CreativeWork" >
	<div class='blog-meta'></div>
	<div class='entry-content-wrapper clearfix standard-content'>
		<header class="entry-content-header">
			<h2 class='post-title entry-title'  itemprop="headline" >	
				<a href='[field:arcurl/]' rel='bookmark' title='[field:title/]'>[field:title/]<span class='post-format-icon minor-meta'></span>
				</a>
			</h2>
			<span class='post-meta-infos'>
				<span class="sent-time-title" >发布时间：</span>
				<time class='date-container minor-meta updated'  itemprop="datePublished" datetime="2017-12-26T14:01:41+00:00" >[field:pubdate function="MyDate('Y-m-d',@me)"/]</time>
			</span>
			<div class="line"></div>
		</header>
		<div class="entry-content"  itemprop="text" ></div>
	</div>
</article>
{/dede:list}



<div class='top3'><nav class='pagination'><span class='current'>1</span><a href='http://www.insigmagroup.com.cn/news/page/2' class='inactive' >2</a><a href='http://www.insigmagroup.com.cn/news/page/3' class='inactive' >3</a><a href='http://www.insigmagroup.com.cn/news/page/2'>&rsaquo;</a><a href='http://www.insigmagroup.com.cn/news/page/46'>&raquo;</a></nav>
</div>                        </div></div>
                        <div class="flex_column av_one_fifth   avia-builder-el-2  el_after_av_four_fifth  avia-builder-el-last  ">
                            <div class="avia-builder-widget-area clearfix  avia-builder-el-3  avia-builder-el-no-sibling ">
                                <div id="annual_archive_widget-2" class="widget clearfix Annual_Archive_Widget">
                                    <h3 class="widgettitle">新闻索引</h3>  
                                    <ul>
                                        <li><a class='active' href='http://www.insigmagroup.com.cn/news'>全部</a></li><li><a href='http://www.insigmagroup.com.cn/2018'>2018</a></li><li><a href='http://www.insigmagroup.com.cn/2017'>2017</a></li><li><a href='http://www.insigmagroup.com.cn/2016'>2016</a></li><li><a href='http://www.insigmagroup.com.cn/2015'>2015</a></li><li><a href='http://www.insigmagroup.com.cn/2014'>2014</a></li>                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                <!--end content-->
                </main>
            </div><!--end container-->
            </div>
        </div><!-- close default .container_wrap element -->




		{dede:include filename="footer.htm"