<article class="post-entry post-entry-type-standard post-entry-9446 post-loop-2 post-parity-even multi-big  post-9446 news type-news status-publish has-post-thumbnail hentry" itemscope="itemscope" itemtype="https://schema.org/CreativeWork" >
        <div class="entry-content-wrapper clearfix standard-content">

            <header class="entry-content-header">

                <span class='search-result-counter '>2</span><h2 class='post-title entry-title'><a title='[field:title/]' href='[field:arcurl/]'  itemprop="headline" >[field:title/]</a></h2>                <span class='post-meta-infos'>
                    <time class='date-container minor-meta updated'  itemprop="datePublished" datetime="2018-04-21T16:49:00+00:00" >
                        [field:stime/]</time>
                    <span class='text-sep'>/</span><span class="blog-categories minor-meta">在：  </span>
                </span>
            </header>

            <div class="entry-content"  itemprop="text" >
</div>        </div>

        <footer class="entry-footer"></footer>
        
        	</article>

	{/dede:list }
	
	



	<nav class='pagination'><span class='current'>1</span><a href='http://www.insigmagroup.com.cn/page/2?s=%E7%A7%91%E6%8A%80&#038;lang=zh-hans' class='inactive' >2</a><a href='http://www.insigmagroup.com.cn/page/3?s=%E7%A7%91%E6%8A%80&#038;lang=zh-hans' class='inactive' >3</a><a href='http://www.insigmagroup.com.cn/page/2?s=%E7%A7%91%E6%8A%80&#038;lang=zh-hans'>&rsaquo;</a><a href='http://www.insigmagroup.com.cn/page/28?s=%E7%A7%91%E6%8A%80&#038;lang=zh-hans'>&raquo;</a></nav>

				<!--end content-->
				</main>

				
			</div><!--end container-->

		</div><!-- close default .container_wrap element -->




					{dede:include filename="footer.htm"