<div class="item second">
				<div class="left"><span class="s-title">[field:title/]</span><span class="title">[field:title/]</span></div>
				<div class="right">
					<p><img class="pic-detail" src="[field:picname/]" alt="专注企业人才培养" /></p>
					<div class="description">
						<p>网新集团以创新为企业文化基因，视优秀员工为企业最宝贵的财富，坚持为员工营造包容及多元化的工作环境：坚持雇佣平等，遵守《劳动合同法》及相关法律法规；始终关注员工的自身成长，鼓励进取，通过管理培训生计划、雏鹰计划等渠道不断提供业务学习、专业提升、分享成果和获得认可的机会，培养员工成为有正气、有激情、爱团队、敢担当、善学习的专业及综合性人才。</p>
						<div class="hidden">
						<p>网新集团积极构筑开放的人才工作平台，广招国际化人才及专家，并定期为浙江大学等高等院校的国际交流生提供实习岗位，并重视沟通与融合，鼓励提出意见和建议，乐于为他们创造更适宜的工作环境。</p>
						<p>作为浙江大学产学研协同创新的重要平台，网新在业务稳步快速发展的同时，积极与浙江大学联合承建的国家级企业技术中心、国家工程技术研究中心、产学研联合研发平台、创新产业孵化中心、博士后工作站等项目，参与国家战略性新兴产业领域的新技术转化和专业人才培养工作，将校企产学研合作推到了一个新高度。</p>
						</div>
						<div><span class="state all">查看所有</span> <span class="state hidden hiding">收起</span></div>
					</div>
				</div>
			</div>