<div id='homepage-business' class='avia-section main_color avia-section-default avia-no-shadow avia-bg-style-scroll  avia-builder-el-4  el_after_av_section  el_before_av_section  container_wrap fullsize'   ><div class='container' ><div class='template-page content  av-content-full alpha units'><div class='post-entry post-entry-type-page post-entry-734'><div class='entry-content-wrapper clearfix'>
			<section class="av_textblock_section"  itemscope="itemscope" itemtype="https://schema.org/CreativeWork" ><div class='avia_textblock '   itemprop="text" ><div class="homepage-title">[field:typename/]</div>
				<div class="homepage-title-under-line"></div>
			</div></section>
			{dede:channelartlist type='top'  typeid='1'}
			<div id='av-magazine-2' class='av-magazine  avia-builder-el-6  el_after_av_textblock  avia-builder-el-last   av-magazine-top-bar-active av-magazine-tabs-active' ><div class='av-magazine-group sort_all'>

			<article class='hentry av-magazine-entry-id-8519 av-magazine-format- av-magazine-type-industry_arena av-magazine-entry-1 av-magazine-entry-small ' ><a href="{dede:field name='typeurl'/}"><div class="icon" alt="{dede:field name='typename'/}"><img width="137" height="141" src="{dede:global.cfg_templets_skin/}/images/2017-01-20-06173149.png" class="attachment-full wp-post-image" alt="04" /></div><div class="right"><header>{dede:field name='typename'/}</header><div class="content">深入挖掘大交通、大金融、大健康三大垂直行业，提供人工智能、大数据为核心的数字化规划设计与咨询方案；并以云计算平台技术为基础，开发人工智能、大数据等应用系统。</div></div></a></article>

			</div></div>
			{/dede:channelartlist} 

		    </div></div></div><!-- close content main div --></div></div>