<div class="item second">
				<div class="left"><span class="s-title">[field:title/]</span><span class="title">[field:title/]</span></div>
				<div class="right">
					<p><img class="pic-detail" src="[field:picname/]" alt="专注企业人才培养" /></p>
					<div class="description">
						<p>[field:body/]</p>
						<div class="hidden">
						[field:body2/]
						</div>
						<div><span class="state all">查看所有</span> <span class="state hidden hiding">收起</span></div>
					</div>
				</div>
			</div>