{dede:channel  type ='self'     row='1'  }
						<li id="menu-item-8556" class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-8550 current_page_item menu-item-8556">
							<a href="[field:typelink/]">
								<span class="menu-title">[field:typename/]</span>
								<span class="dot">•</span>
							</a>
						</li>
						{/dede:channel}
						<!-- <li id="menu-item-8555" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8555">
							<a href="http://www.insigmagroup.com.cn/industry/green">
								<span class="menu-title">绿色产业</span>
								<span class="dot">•</span>
							</a>
						</li> -->