<section class="av_textblock_section"  itemscope="itemscope" itemtype="https://schema.org/CreativeWork" ><div class='avia_textblock '   itemprop="text" ><div class="big-title">
<div class="title">浙大网新集团企业社会责任</div>
</div>
</div></section>

<section class="av_textblock_section"  itemscope="itemscope" itemtype="https://schema.org/CreativeWork" ><div class='avia_textblock '   itemprop="text" ><div class="concept">
<p><span class="title">浙大网新集团企业社会责任</span></p>
<div class="description indent">[field:body function='cn_substr(html2text(@me),600)'/]</div>
</div>
</div></section>