<field:body itemname="文章内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="" page="split">	
</field:body>	

<field:download itemname="文章下载" autofield="1" notsend="0" type="addon" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:download>

<field:video itemname="视频地址" autofield="1" notsend="0" type="media" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:video>

