<div class="item first">
		<div class="left"><span class="s-title">[field:title/]</span><span class="title">[field:title/]</span></div>
		<div class="right">
			<p><img class="pic-detail" src="[field:picname/]" alt="贡献新型城镇化建设" /></p>
			<div class="description">[field:body /]</div>
			<div><span class="state all">查看所有</span> <span class="state hidden hiding">收起</span></div>
		</div>

	</div>