
			<div id='homepage-about' class='avia-section main_color avia-section-default avia-no-shadow avia-bg-style-scroll  avia-builder-el-1  el_after_av_layerslider  el_before_av_section  av-minimum-height av-minimum-height-50 container_wrap fullsize' style = 'background-repeat: no-repeat; background-image: url({dede:global.cfg_templets_skin/}/images/2015-11-17-03331842.png); background-attachment: scroll; background-position: bottom center; ' data-section-bg-repeat='no-repeat' ><div class='container' ><div class='template-page content  av-content-full alpha units'><div class='post-entry post-entry-type-page post-entry-734'><div class='entry-content-wrapper clearfix'>
				<section class="av_textblock_section"  itemscope="itemscope" itemtype="https://schema.org/CreativeWork" >
				<div class='avia_textblock '   itemprop="text" >
				<div class="homepage-title">[field:typename/]</div>
					<div class="homepage-title-under-line"></div>
				</div></section>
				<div id='av-magazine-1' class='av-magazine  avia-builder-el-3  el_after_av_textblock  avia-builder-el-last   av-magazine-top-bar-active av-magazine-tabs-active' ><div class='av-magazine-group sort_all'><article class='hentry av-magazine-entry-id-8514 av-magazine-format- av-magazine-type-homepage_about av-magazine-entry-1 av-magazine-entry-small ' ><div class="pic" alt=""><img width="1147" height="326" src="{dede:global.cfg_templets_skin/}/images/2017-01-20-0617272.png" class="attachment-full wp-post-image" alt="01" /></div><div class="content">{dede:field.content/}</div><div class="btn-top"><a href='/homepage/about-insigma-group'><span class='btn btn-read-more'>查看更多</span></a></div></article></div></div>

			</div></div></div><!-- close content main div --></div></div>
			