<article class='hentry av-magazine-entry-id-8519 av-magazine-format- av-magazine-type-industry_arena av-magazine-entry-1 av-magazine-entry-small ' ><a href="{dede:field name='typeurl'/}"><div class="icon" alt="{dede:field name='typename'/}"><img width="137" height="141" src="[field:picname/]" class="attachment-full wp-post-image" alt="04" /></div><div class="right"><header>{dede:field.title/}</header>

			<div class="content">{dede:field.content/}</div>
			</div></a></article>