<?php
$z[0]=Array("picname","",158,174);
$z[1]=Array("arcurl","",277,292);
$z[2]=Array("fulltitle","",301,319);
$z[3]=Array("title","",321,403);
$z[3][4]['function']="( strlen(\"@me\")>40 ? cn_substr(\"@me\",40).\"…\" : \"@me\" )";
$z[4]=Array("arcurl","",431,446);
$z[5]=Array("fulltitle","",455,473);
$z[6]=Array("pubdate","",506,553);
$z[6][4]['function']="MyDate('Y-m-d',@me)";
$z[7]=Array("description","",580,670);
$z[7][4]['function']="( strlen(\"@me\")>170 ? cn_substr(\"@me\",170).\"…\" : \"@me\" )";

?>