<li id="menu-item-8677" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-top-level menu-item-top-level-2"><a href="{dede:field name='typeurl'/}" itemprop="url"><span class="avia-bullet"></span><span class="avia-menu-text">{dede:field name='typename'/}</span><span class="avia-menu-fx"><span class="avia-arrow-wrap"><span class="avia-arrow"></span></span></span></a>


							<!-- <ul class="sub-menu">
								<li id="menu-item-8575" class="menu-item menu-item-type-post_type menu-item-object-page"><a href="http://www.insigmagroup.com.cn/industry/smart" itemprop="url"><span class="avia-bullet"></span><span class="avia-menu-text">智慧产业</span></a></li>
								<li id="menu-item-8574" class="menu-item menu-item-type-post_type menu-item-object-page"><a href="http://www.insigmagroup.com.cn/industry/green" itemprop="url"><span class="avia-bullet"></span><span class="avia-menu-text">绿色产业</span></a></li>
							</ul> -->
						</li>