<section class="av_textblock_section"  itemscope="itemscope" itemtype="https://schema.org/CreativeWork" ><div class='avia_textblock '   itemprop="text" ><div class="big-title">
<div class="title">[field:title/]</div>
</div>
</div></section>

<section class="av_textblock_section"  itemscope="itemscope" itemtype="https://schema.org/CreativeWork" ><div class='avia_textblock '   itemprop="text" ><div class="concept">
<p><span class="title">[field:title/]</span></p>
<div class="description indent">[field:description/]</div>
</div>
</div></section>