<article class="item more">
	<img width="397" height="245" src="[field:picname/]" class="attachment-post-thumbnail wp-post-image" alt="2016-12-22-08231370" />
	<header>[field:title/]</header>
	<div class="content">[field:title/]
				<a class="read-more" href="#item3" data="<article class='item'><header id=item3>[field:title/]</header><div class='content'><img src='[field:picname/]' alt='2016-12-22-08231370' width='397' height='245' class='aligncenter size-full wp-image-8512' />

		<p>2014年4月，网新集团旗下网新恒天软件有限公司与国家质检总局网上电子商务风险监控中心就大屏可视化项目正式签署合作协议。该监控中心是国家质检总局直属事业单位，其主要职能是对网上电子商务行为进行风险监控，对投诉举报中心受理的问题商品进行抽样检查，最后对问题卖家以及背后的生产企业进行查处。</p>



		</div></article>">
		[查看更多]</a>
	</div>
</article>