<article class="item more">
	<img width="397" height="245" src="[field:picname/]" class="attachment-post-thumbnail wp-post-image" alt="2016-12-22-08231370" />
	<header>[field:title/]</header>
	<div class="content">[field:title/]
				<a class="read-more" href="#item3" data="<article class='item'><header id=item3>[field:title/]</header><div class='content'><img src='[field:picname/]' alt='2016-12-22-08231370' width='397' height='245' class='aligncenter size-full wp-image-8512' />

		<p>[field:body/]</p>



		</div></article>">
		[查看更多]</a>
	</div>
</article>