<section class="av_textblock_section"  itemscope="itemscope" itemtype="https://schema.org/CreativeWork" ><div class='avia_textblock '   itemprop="text" ><div class="big-title">
<div class="title">[field:title/]</div>
</div>
</div></section>

<section class="av_textblock_section"  itemscope="itemscope" itemtype="https://schema.org/CreativeWork" ><div class='avia_textblock '   itemprop="text" ><div class="concept">
<span class="title">[field:title/]11111</span>
<div class="description indent">[field:body function='cn_substr(html2text(@me),600)'/]</div>
</div>
</div></section>