<div class="item first">
<div class="left"><span class="s-title">[field:title/]</span><span class="title">[field:title/]</span></div>
<div class="right">
<p><img class="pic-detail" src="[field:picname/]" alt="贡献新型城镇化建设" /></p>
<div class="description">
<p>浙大网新集团是以促进“绿色智慧城市”发展为目标，以产学研协同创新系统为依托，致力于为中国新型城镇化建设提供整体解决方案的国际化高科技企业控股集团。拥有浙大网新、众合机电等多家上市公司，业务涵盖智慧园区、轨道交通、能源环保、智慧政务、智慧商务及智慧生活等多个领域。</p>
<div class="hidden">
<p>在国家“创新驱动发展”的战略引领下，浙大网新集团凭借“科技+金融+管理”一体化的综合服务能力，依靠大数据、云计算和物联网的技术优势，以城市科技综合体、城市基础建设为平台，通过产业定位、技术研发与转化、招商运营、科技投资、资金及财务管理、建设管理、资产运营管理等全方位、立体式的业务服务，促进产城融合、提高公共服务效率、提升企业竞争力，推动中国新型城镇化建设的发展。</p>
</div>
<div><span class="state all">查看所有</span> <span class="state hidden hiding">收起</span></div>
</div>
</div>
</div>