<article class='post-entry post-entry-type-standard post-entry-9392 post-loop-1 post-parity-odd top3 is-top-3 post with-slider post-9392 news type-news status-publish has-post-thumbnail hentry'  itemscope="itemscope" itemtype="https://schema.org/CreativeWork" >
                    				<div class='blog-meta'>
                    					<img src="[field:picname/]">
                    				</div>
                    				<div class='entry-content-wrapper clearfix standard-content'>
                    					<header class="entry-content-header">
                    						<h2 class='post-title entry-title'  itemprop="headline" >	
                    							<a href='[field:arcurl/]' rel='bookmark' title='[field:title/]'>[field:title/]<span class='post-format-icon minor-meta'></span></a>
                    						</h2>
                    						<span class='post-meta-infos'>
                    							<span class="sent-time-title" >发布时间：</span>
                    							<time class='date-container minor-meta updated'  itemprop="datePublished" datetime="2018-02-13T16:00:09+00:00" >[field:pubdate function="MyDate('Y-m-d',@me)"/]</time>
                    						</span>
                    						<div class="line"></div>
                    					</header>
                    					<div class="entry-content"  itemprop="text" >[field:shorttitle/]</div>
                    				</div>
                    			</article>