<article class="item more">
	<img width="397" height="245" src="[field:picname/]" class="attachment-post-thumbnail wp-post-image" alt="2016-12-22-08231370" />
	<header>[field:title/]</header>
	<div class="content">[field:title/]
				<a class="read-more" href="#item3" data="<article class='item'><header id=item3>国家质检总局网上电子商务风险监控大屏幕可视化系统</header><div class='content'><img src='/admin/images/2017-01-20-06240753.png' alt='2016-12-22-08231370' width='397' height='245' class='aligncenter size-full wp-image-8512' />

		<p>2014年4月，网新集团旗下网新恒天软件有限公司与国家质检总局网上电子商务风险监控中心就大屏可视化项目正式签署合作协议。该监控中心是国家质检总局直属事业单位，其主要职能是对网上电子商务行为进行风险监控，对投诉举报中心受理的问题商品进行抽样检查，最后对问题卖家以及背后的生产企业进行查处。</p>

		<p>在此次项目开发过程中，开发团队秉持一贯的高要求、高标准以及快速响应的专业服务态度，对客户方获取的电子商务数据进行大数据分析，并对分析结果进行电子商务行为分析，以帮助客户进行抽样决策。分析数据及整个行为流程需以可视化图形的方式在 69 寸、分辨率 2560×2048 的大屏幕上显示以便监控。</p>

		<p>恒天软件的 UED (User Experience Desgin)团队承接了此大屏幕可视化系统的设计和开发，充分发挥团队的数据图形创意设计以及高端图形开发能力，在短期内即高效迅速地交付了项目成果，为今后恒天软件的数据可视化项目能力和业务实际操作经验打下了更扎实的基础。</p></div></article>">
		[查看更多]</a>
	</div>
</article>