<?php
$z[0]=Array("picname","",158,174);
$z[1]=Array("id","",290,301);
$z[2]=Array("fulltitle","",310,328);
$z[3]=Array("title","",330,412);
$z[3][4]['function']="( strlen(\"@me\")>40 ? cn_substr(\"@me\",40).\"…\" : \"@me\" )";
$z[4]=Array("id","",453,464);
$z[5]=Array("fulltitle","",473,491);
$z[6]=Array("pubdate","",524,571);
$z[6][4]['function']="MyDate('Y-m-d',@me)";
$z[7]=Array("description","",598,688);
$z[7][4]['function']="( strlen(\"@me\")>170 ? cn_substr(\"@me\",170).\"…\" : \"@me\" )";

?>