<?php
$z[0]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",82,165);
$z[0][4]['typeid']="1";
$z[1]=Array("channelartlist","\r\n      <li><a href=\"{dede:field name='typeurl'/}\" class=\"has-sub\">{dede:field name='typename'/}</a>\r\n       <ul>\r\n       \r\n        {dede:sql sql='Select * from dede_arctype where reid=~id~  and ishidden != 1 ORDER BY sortrank limit 0,20'}\r\n        <li><a href=\"[field:typedir function='str_replace(\"{cmspath}\",\"\",@me)'/]\">[field:typename/]</a></li>\r\n        {/dede:sql}       \r\n        \r\n       </ul>\r\n      </li>\r\n      ",199,689);
$z[1][4]['typeid']="1";
$z[2]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",743,826);
$z[2][4]['typeid']="2";
$z[3]=Array("channelartlist","\r\n      <li><a href=\"{dede:field name='typeurl'/}\" class=\"has-sub\">{dede:field name='typename'/}</a>\r\n       <ul>\r\n       \r\n        {dede:sql sql='Select * from dede_arctype where reid=~id~  and ishidden != 1 ORDER BY sortrank limit 0,20'}\r\n        <li><a href=\"[field:typedir function='str_replace(\"{cmspath}\",\"\",@me)'/]\">[field:typename/]</a></li>\r\n        {/dede:sql}       \r\n        \r\n       </ul>\r\n      </li>\r\n      ",860,1350);
$z[3][4]['typeid']="2";
$z[4]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",1404,1487);
$z[4][4]['typeid']="3";
$z[5]=Array("channelartlist","\r\n      <li><a href=\"{dede:field name='typeurl'/}\" class=\"has-sub\">{dede:field name='typename'/}</a>\r\n       <ul>\r\n       \r\n        {dede:sql sql='Select * from dede_arctype where reid=~id~  and ishidden != 1 ORDER BY sortrank limit 0,20'}\r\n        <li><a href=\"[field:typedir function='str_replace(\"{cmspath}\",\"\",@me)'/]\">[field:typename/]</a></li>\r\n        {/dede:sql}       \r\n        \r\n       </ul>\r\n      </li>\r\n      ",1521,2011);
$z[5][4]['typeid']="3";
$z[6]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",2065,2148);
$z[6][4]['typeid']="4";
$z[7]=Array("channelartlist","\r\n      <li><a href=\"{dede:field name='typeurl'/}\" class=\"has-sub\">{dede:field name='typename'/}</a>\r\n       <ul>\r\n       \r\n        {dede:sql sql='Select * from dede_arctype where reid=~id~  and ishidden != 1 ORDER BY sortrank limit 0,20'}\r\n        <li><a href=\"[field:typedir function='str_replace(\"{cmspath}\",\"\",@me)'/]\">[field:typename/]</a></li>\r\n        {/dede:sql}       \r\n        \r\n       </ul>\r\n      </li>\r\n      ",2182,2672);
$z[7][4]['typeid']="4";
$z[8]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",2726,2809);
$z[8][4]['typeid']="5";
$z[9]=Array("channelartlist","\r\n      <li><a href=\"{dede:field name='typeurl'/}\" class=\"has-sub\">{dede:field name='typename'/}</a>\r\n       <ul>\r\n       \r\n        {dede:sql sql='Select * from dede_arctype where reid=~id~  and ishidden != 1 ORDER BY sortrank limit 0,20'}\r\n        <li><a href=\"[field:typedir function='str_replace(\"{cmspath}\",\"\",@me)'/]\">[field:typename/]</a></li>\r\n        {/dede:sql}       \r\n        \r\n       </ul>\r\n      </li>\r\n      ",2843,3333);
$z[9][4]['typeid']="5";
$z[10]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",3387,3471);
$z[10][4]['typeid']="52";
$z[11]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",3541,3625);
$z[11][4]['typeid']="44";
$z[12]=Array("channelartlist","\r\n    <li><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>&#124;</li>\r\n    ",3740,3914);
$z[12][4]['typeid']="45,46,47";

?>