<?php
$z[0]=Array("global","",797,823);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",864,891);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",929,959);
$z[2][4]['name']="cfg_description";
$z[3]=Array("include","",982,1019);
$z[3][4]['filename']="head_m.htm";
$z[4]=Array("arclist","\r\n    <article class=\"startbottom\">\r\n     <div id=\"c26\" class=\"csc-default\">\r\n      <div class=\"news-latest-item\">\r\n       <div class=\"news-latest-image\"><img src=\"[field:picname/]\" width=\"64\" height=\"52\"   alt=\"\" ></div>\r\n       <div class=\"news-latest-text\">\r\n        <h2><a href=\"view.php?aid=[field:id/]\" title=\"[field:fulltitle/]\">[field:title function='( strlen(\"@me\")>40 ? cn_substr(\"@me\",40).\"…\" : \"@me\" )'/]</a></h2>\r\n        <a href=\"view.php?aid=[field:id/]\" title=\"[field:fulltitle/]\"><span class=\"news-latest-date\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/] &#124;</span>\r\n        <p>[field:description function='( strlen(\"@me\")>170 ? cn_substr(\"@me\",170).\"…\" : \"@me\" )'/]</p>\r\n        </a> </div>\r\n      </div>\r\n     </div>\r\n    </article>\r\n    ",1263,2097);
$z[4][4]['typeid']="47";
$z[4][4]['row']="3";
$z[4][4]['titlelen']="80";
$z[5]=Array("include","",2157,2200);
$z[5][4]['filename']="side_right_m.htm";
$z[6]=Array("include","",2219,2258);
$z[6][4]['filename']="footer_m.htm";

?>