<?php
$z[0]=Array("global","",579,605);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",646,673);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",711,741);
$z[2][4]['name']="cfg_description";
$z[3]=Array("include","",1278,1313);
$z[3][4]['filename']="head.htm";
$z[4]=Array("arclist","\r\n    <article class=\"startbottom\">\r\n     <div id=\"c26\" class=\"csc-default\">\r\n      <div class=\"news-latest-item\">\r\n       <div class=\"news-latest-image\"><img src=\"[field:picname/]\" width=\"64\" height=\"52\"   alt=\"\" ></div>\r\n       <div class=\"news-latest-text\">\r\n        <h2><a href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\">[field:title function='( strlen(\"@me\")>40 ? cn_substr(\"@me\",40).\"…\" : \"@me\" )'/]</a></h2>\r\n        <a href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\"><span class=\"news-latest-date\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/] &#124;</span>\r\n        <p>[field:description function='( strlen(\"@me\")>170 ? cn_substr(\"@me\",170).\"…\" : \"@me\" )'/]</p>\r\n        </a> </div>\r\n      </div>\r\n     </div>\r\n    </article>\r\n    ",4724,5540);
$z[4][4]['typeid']="47";
$z[4][4]['row']="3";
$z[4][4]['titlelen']="80";
$z[5]=Array("include","",5602,5643);
$z[5][4]['filename']="side_right.htm";
$z[6]=Array("include","",5676,5713);
$z[6][4]['filename']="footer.htm";

?>