<?php
$typeArr[1] = '产业布局';
$typeArr[2] = '创新创业';
$typeArr[3] = '新闻中心';
$typeArr[4] = '人才招聘';
$typeArr[5] = '联系我们';
$typeArr[6] = '智慧产业';
$typeArr[7] = '绿色产业';
$typeArr[8] = '金融';
$typeArr[9] = '技术';
$typeArr[10] = '空间';
$typeArr[11] = 'ppp';
$typeArr[12] = '关于我们';
$typeArr[13] = '贡献';
$typeArr[14] = '专注';
$typeArr[15] = '关注';
$typeArr[20] = '2017';
$typeArr[16] = '经典案例';
$typeArr[18] = '社会责任';
$typeArr[21] = '2016';
$typeArr[19] = '2018';
$typeArr[22] = '2015';
$typeArr[23] = '2014';
?>