<?php
$typeArr[2] = '产业布局';
$typeArr[3] = '新闻中心';
$typeArr[4] = '人才招聘';
$typeArr[5] = '联系我们';
$typeArr[24] = '产业布局old';
$typeArr[25] = '锐得电子';
$typeArr[26] = '锐启文化';
$typeArr[27] = '云秤数据';
$typeArr[9] = '晶苓电子';
$typeArr[28] = '新增';
$typeArr[12] = '关于我们';
$typeArr[13] = '贡献';
$typeArr[14] = '专注';
$typeArr[15] = '关注';
$typeArr[20] = '2017';
$typeArr[16] = '经典案例';
$typeArr[18] = '社会责任';
$typeArr[21] = '2016';
$typeArr[19] = '2018';
$typeArr[22] = '2015';
$typeArr[23] = '2014';
?>